import type { Metadata } from "next";
import StepBar from "./components/StepBar";
export const metadata: Metadata = {
  title: "Auth Register",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="max-w-[1440px] mx-auto px-2 ">
      <StepBar />
      {children}
    </div>
  );
}
