export const categories: string[] = [
  "programming",
  "data science",
  "technology",
  "self improvement",
  "writing",
  "relationship",
  "machine learning",
  "productivity",
  "politics",
  "coding"
];


export const topics: string[] = [
  "coding",
  "sleepping",
  "eating",
  "gym",
  "programming",
  "dasturlash",
  "data science",
  "texnologiya",
  "shaxsiy rivojlanish",
  "yozish",
  "ishqiy munosabatlar",
  "ML",
  "samaradorlik",
  "siyosat",
  "kod yozish",
  "moliyaviy erkinlik",
  "tadbirkorlik",
  "sun'iy intellekt",
  "salomatlik va sport",
  "psixologiya",
  "blockchain",
  "investitsiyalar",
  "ta'lim",
  "bisnes",
  "marketing",
  "liderlik",
  "ijodkorlik",
  "kiberxavfsizlik",
  "dizayn",
  "ijtimoiy tarmoqlar",
  "sayohat",
  "sport",
  "atrof-muhit",
  "falsafa",
  "iqtisodiyot",
  "tarix",
  "matematika",
  "chet tillari",
  "musiqa",
  "kiber o'yinlar",
  "startaplar",
  "taromq",
  "veb-dasturlash",
  "mobil dasturlash",
  "bulut",
  "virtual haqiqat",
  "kvant fizikasi",
  "iqlim o'zgarishi",
  "ilm-fan",
  "biologiya",
  "fizika",
  "kosmosni kashf etish",
  "ruhiy salomatlik",
  "internet do'konlar",
  "elektron tijorat",
  "robototexnika",
];

export const moreTopics = [
  "madaniyat",
  "she'riyat",
  "ovqat tayyorlash",
  "ta'mirlash",
  "fotografiya",
  "film va kino",
  "oila",
  "bolalar tarbiyasi",
  "sayohat qilish",
  "qishloq xo'jaligi",
  "suvni tejash",
  "mobillik",
  "ijodiy yozish",
  "qurilish",
  "transport",
  "tibbiyot",
  "atirgul yetishtirish",
  "kompyuter o'yinlari",
  "bog'dorchilik",
  "parvarish",
];